export const kText = {
  theWedding: "The Wedding",
  name: "Kiki & Tirsa",
  kepada: "Kepada",
  bukaUndangan: "Buka Undangan",
  date: new Date(Date.parse("11 Dec 2023 00:00:00 GMT")),
  atasBerkahRahmat: "Atas Berkah dan Rahmat Allah Subhanallahu Wa Ta'ala. ",
  kamiMengundang:
    "Kami mengundang Bapak/Ibu/Saudara/i ​​serta kerabat sekalian untuk menghadiri acara pernikahan kami :",
  ayat1:
    "وَمِنْ اٰيٰتِهٖٓ اَنْ خَلَقَ لَكُمْ مِّنْ اَنْفُسِكُمْ اَزْوَاجًا لِّتَسْكُنُوْٓا اِلَيْهَا وَجَعَلَ بَيْنَكُمْ مَّوَدَّةً وَّرَحْمَةً ۗاِنَّ فِيْ ذٰلِكَ لَاٰيٰتٍ لِّقَوْمٍ يَّتَفَكَّرُوْنَ",
  ayat1Arti: `"Dan di antara tanda-tanda (kebesaran)-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya, dan Dia menjadikan di antaramu rasa kasih dan sayang. Sungguh, pada yang demikian itu benar-benar terdapat tanda-tanda (kebesaran Allah) bagi kaum yang berpikir."`,
  ayat1Surat: "(QS Ar-Rum: 21)",
  namaPengantin1: "Kiki",
  ayahPengantin1: "Nama Ayah Pengantin 1",
  ibuPengantin1: "Nama Ibu Pengantin 1",
  anakKePengantin1: "Pertama",
  alamatPengantin1:
    "Beralamat di Plosokuning III RT 13/05, Minomartani, Ngaglik, Sleman",
  namaPengantin2: "Tirsa",
  ayahPengantin2: "Fulan",
  ibuPengantin2: "Fulanah",
  alamatPengantin2:
    "Beralamat di Plosokuning III RT 13/05, Minomartani, Ngaglik, Sleman",
  anakKePengantin2: "Kedua",
  saveTheDate: "Save The Date",
  waktuPernikahan: "11:30 WIB - 12:30 WIB",
  pukul: "Pukul",
  venue: "Gedung Serbaguna Kalitirto",
  mapLokasiAcara: "Map Lokasi Acara",
  merupakanSuatuKehormatan:
    "Merupakan suatu kehormatan dan kebahagiaan bagi kami sekeluarga, apabila Bapak/Ibu/Saudara/i ​​berkenan hadir dan memberikan doa restu. ",
  memberikanDoaRestu:
    "memberikan doa restu. Atas kehadiran dan doa restunya, kami mengucapkan terima kasih.",
  linkMaps: "https://maps.app.goo.gl/ZsafwexTP5KwTCr3A",
  acaraAkad: "Acara Akad",
  hariAcaraAkad: "Senin, 11 Desember 2023",
  waktuAcaraAkad: "09.00 - 09.30 WIB",
  tempatAcaraAkad: "Koffie Mabelas [Koma]",
  acaraResepsi: "Acara Resepsi",
  hariAcaraResepsi: "Senin, 11 Desember 2023",
  waktuAcaraResepsi: "09.00 - 09.30 WIB",
  tempatAcaraResepsi: "Koffie Mabelas [Koma]",
  kehadiran: "Kehadiran",
  nama: "Nama",
  ucapan: "Ucapan",
  kirim: "Kirim",
  hadir: "Hadir",
  tidakHadir: "Tidak Hadir",
  totalUcapan: "Total Ucapan",
  orangMenyatakanHadir: "Orang Menyatakan Hadir",
  ourGallery: "Our Gallery",
  terimaKasih: "Terimakasih",
  merupakanSuatuKebahagiaan:
    "Merupakan Suatu Kebahagiaan dan Kehormatan bagi Kami, Apabila Bapak/Ibu/Saudara/i, Berkenan Hadir di Acara kami",
  instagramId: "abd.harits19",
};
